<?php

namespace Database\Seeders;

use App\Models\Job;
use App\Models\TechSpecialty;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $specialtyIds = TechSpecialty::query()->pluck('id', 'name');

        $jobs = [
            [
                'title' => 'مطور React أول',
                'company_name' => 'SyriaDev Studio',
                'logo' => '💻',
                'location' => 'عن بُعد',
                'employment_type' => 'دوام كامل',
                'salary_min' => 1200,
                'salary_max' => 1800,
                'remote_type' => 'full-remote',
                'timezone' => 'UTC+2',
                'is_syria_friendly' => true,
                'payment_methods' => ['Wise', 'PayPal'],
                'skills' => ['React', 'TypeScript', 'Node.js'],
                'tags' => ['full-time', 'remote', 'frontend'],
                'tag_labels' => [
                    ['t' => 'عن بُعد 🌐', 'c' => 'teal'],
                    ['t' => 'Frontend', 'c' => 'blue'],
                    ['t' => 'Senior', 'c' => 'gold'],
                ],
                'tech_specialty' => 'Frontend',
                'is_new' => true,
                'is_featured' => true,
                'order' => 1,
                'published_at' => Carbon::now()->subDays(2),
                'description' => 'نبحث عن مطور React موهوب للانضمام لفريقنا السوري عن بُعد. ستعمل على منتجات SaaS تخدم السوق العربي والعالمي.',
                'responsibilities' => ['تطوير واجهات React/TypeScript عالية الجودة', 'التعاون مع فريق Backend على REST APIs', 'كتابة اختبارات ومراجعة كود', 'المشاركة في قرارات المنتج'],
                'requirements' => ['3+ سنوات React/TypeScript', 'خبرة Node.js', 'Git و CI/CD', 'عربي وإنجليزي'],
                'benefits' => ['راتب بالدولار', 'ساعات مرنة', 'تدريب مستمر', 'معدات عمل'],
            ],
            [
                'title' => 'مهندس DevOps',
                'company_name' => 'CloudBridge EU',
                'logo' => '☁️',
                'location' => 'عن بُعد · أوروبا',
                'employment_type' => 'دوام كامل',
                'salary_min' => 2000,
                'salary_max' => 2800,
                'remote_type' => 'full-remote',
                'timezone' => 'UTC+1',
                'is_syria_friendly' => true,
                'payment_methods' => ['Wise', 'Bank Transfer'],
                'skills' => ['Docker', 'Kubernetes', 'AWS', 'Terraform'],
                'tags' => ['full-time', 'remote', 'devops'],
                'tag_labels' => [
                    ['t' => 'عن بُعد 🌐', 'c' => 'teal'],
                    ['t' => 'DevOps', 'c' => 'blue'],
                    ['t' => 'Senior', 'c' => 'gold'],
                ],
                'tech_specialty' => 'DevOps',
                'is_new' => true,
                'is_featured' => true,
                'order' => 2,
                'published_at' => Carbon::now()->subDay(),
                'description' => 'شركة أوروبية تبحث عن مهندس DevOps للعمل عن بُعد مع فريق موزع. خبرة سورية مرحب بها.',
                'responsibilities' => ['إدارة البنية السحابية AWS', 'أتمتة CI/CD pipelines', 'مراقبة الأنظمة', 'تحسين الأمان'],
                'requirements' => ['4+ سنوات DevOps', 'AWS certified preferred', 'Linux و scripting', 'إنجليزي متقدم'],
                'benefits' => ['عقد B2B', 'إجازة 28 يوم', 'ميزانية تعلم', 'تأمين صحي'],
            ],
            [
                'title' => 'مصمم UI/UX',
                'company_name' => 'Pixel Damascus',
                'logo' => '🎨',
                'location' => 'دمشق · هجين',
                'employment_type' => 'هجين',
                'salary_min' => 800,
                'salary_max' => 1200,
                'remote_type' => 'hybrid',
                'timezone' => 'UTC+2',
                'is_syria_friendly' => true,
                'payment_methods' => ['PayPal', 'Wise'],
                'skills' => ['Figma', 'UI Design', 'Prototyping'],
                'tags' => ['hybrid', 'design'],
                'tag_labels' => [
                    ['t' => 'هجين', 'c' => 'blue'],
                    ['t' => 'UI/UX', 'c' => 'gold'],
                ],
                'tech_specialty' => 'UI/UX',
                'is_new' => false,
                'is_featured' => false,
                'order' => 3,
                'published_at' => Carbon::now()->subDays(3),
                'description' => 'ستوديو تصميم دمشقي يبحث عن مصمم UI/UX لمنتجات رقمية ومواقع الشركات.',
                'responsibilities' => ['تصميم واجهات Figma', 'اختبار المستخدم', 'Design system', 'التعاون مع المطورين'],
                'requirements' => ['2+ سنوات UI/UX', 'Portfolio قوي', 'Figma متقدم'],
                'benefits' => ['بيئة إبداعية', 'مشاريع متنوعة', 'مرونة'],
            ],
            [
                'title' => 'محلل بيانات',
                'company_name' => 'DataSyria',
                'logo' => '📊',
                'location' => 'عن بُعد',
                'employment_type' => 'عن بُعد',
                'salary_min' => 1000,
                'salary_max' => 1500,
                'remote_type' => 'full-remote',
                'timezone' => 'UTC+2',
                'is_syria_friendly' => true,
                'payment_methods' => ['Wise'],
                'skills' => ['Python', 'SQL', 'Power BI'],
                'tags' => ['remote', 'data'],
                'tag_labels' => [
                    ['t' => 'عن بُعد 🌐', 'c' => 'teal'],
                    ['t' => 'Data', 'c' => 'blue'],
                ],
                'tech_specialty' => 'Data',
                'is_new' => false,
                'is_featured' => true,
                'order' => 4,
                'published_at' => Carbon::now()->subDays(5),
                'description' => 'تحليل بيانات لقطاع التجارة الإلكترونية السورية والإقليمية.',
                'responsibilities' => ['بناء dashboards', 'تحليل البيانات', 'تقارير للإدارة'],
                'requirements' => ['Python و SQL', 'Power BI أو Tableau', 'إحصاء'],
                'benefits' => ['Remote كامل', 'USD', 'نمو مهني'],
            ],
            [
                'title' => 'مطور Flutter',
                'company_name' => 'Mobile Aleppo',
                'logo' => '📱',
                'location' => 'حلب · عن بُعد',
                'employment_type' => 'دوام كامل',
                'salary_min' => 900,
                'salary_max' => 1400,
                'remote_type' => 'full-remote',
                'timezone' => 'UTC+2',
                'is_syria_friendly' => true,
                'payment_methods' => ['PayPal', 'Wise'],
                'skills' => ['Flutter', 'Dart', 'Firebase'],
                'tags' => ['full-time', 'mobile'],
                'tag_labels' => [
                    ['t' => 'عن بُعد 🌐', 'c' => 'teal'],
                    ['t' => 'Flutter', 'c' => 'gold'],
                ],
                'tech_specialty' => 'Mobile',
                'is_new' => true,
                'is_featured' => true,
                'order' => 5,
                'published_at' => Carbon::now(),
                'description' => 'تطبيقات جوال للسوق العربي — فريق حلب يعمل عن بُعد.',
                'responsibilities' => ['تطوير تطبيقات Flutter', 'تكامل APIs', 'نشر App Store/Play'],
                'requirements' => ['2+ سنوات Flutter', 'Firebase', 'State management'],
                'benefits' => ['فريق شاب', 'مشاريع حقيقية', 'USD'],
            ],
            [
                'title' => 'QA Engineer',
                'company_name' => 'QualityFirst Remote',
                'logo' => '🔍',
                'location' => 'عن بُعد',
                'employment_type' => 'دوام كامل',
                'salary_min' => 700,
                'salary_max' => 1100,
                'remote_type' => 'full-remote',
                'timezone' => 'UTC+3',
                'is_syria_friendly' => true,
                'payment_methods' => ['Wise', 'PayPal'],
                'skills' => ['Selenium', 'Cypress', 'Manual Testing'],
                'tags' => ['full-time', 'qa'],
                'tag_labels' => [
                    ['t' => 'عن بُعد 🌐', 'c' => 'teal'],
                    ['t' => 'QA', 'c' => 'accent'],
                ],
                'tech_specialty' => 'QA',
                'is_new' => false,
                'is_featured' => true,
                'order' => 6,
                'published_at' => Carbon::now()->subWeek(),
                'description' => 'اختبار منتجات SaaS — manual و automated testing.',
                'responsibilities' => ['كتابة test cases', 'automation', 'bug reporting'],
                'requirements' => ['1+ سنة QA', 'Cypress أو Selenium', 'attention to detail'],
                'benefits' => ['Remote', 'تدريب automation', 'USD'],
            ],
            [
                'title' => 'Backend Node.js',
                'company_name' => 'TechLatakia',
                'logo' => '⚙️',
                'location' => 'اللاذقية · عن بُعد',
                'employment_type' => 'دوام كامل',
                'salary_min' => 1100,
                'salary_max' => 1700,
                'remote_type' => 'full-remote',
                'timezone' => 'UTC+2',
                'is_syria_friendly' => true,
                'payment_methods' => ['Wise'],
                'skills' => ['Node.js', 'PostgreSQL', 'Redis'],
                'tags' => ['full-time', 'backend'],
                'tag_labels' => [
                    ['t' => 'عن بُعد 🌐', 'c' => 'teal'],
                    ['t' => 'Backend', 'c' => 'blue'],
                ],
                'tech_specialty' => 'Backend',
                'is_new' => true,
                'is_featured' => true,
                'order' => 7,
                'published_at' => Carbon::now()->subDays(2),
                'description' => 'APIs و microservices لمنصة توصيل محلية.',
                'responsibilities' => ['REST/GraphQL APIs', 'Database design', 'Performance optimization'],
                'requirements' => ['3+ سنوات Node.js', 'PostgreSQL', 'Redis'],
                'benefits' => ['Startup environment', 'Equity optional', 'USD'],
            ],
            [
                'title' => 'Product Manager',
                'company_name' => 'RemoteMENA',
                'logo' => '📋',
                'location' => 'عن بُعد · MENA',
                'employment_type' => 'دوام كامل',
                'salary_min' => 1500,
                'salary_max' => 2200,
                'remote_type' => 'full-remote',
                'timezone' => 'UTC+2',
                'is_syria_friendly' => true,
                'payment_methods' => ['Wise', 'PayPal'],
                'skills' => ['Product', 'Agile', 'Analytics'],
                'tags' => ['full-time', 'pm'],
                'tag_labels' => [
                    ['t' => 'عن بُعد 🌐', 'c' => 'teal'],
                    ['t' => 'PM', 'c' => 'accent'],
                ],
                'tech_specialty' => 'Product',
                'is_new' => false,
                'is_featured' => false,
                'order' => 8,
                'published_at' => Carbon::now()->subDays(3),
                'description' => 'إدارة منتج تقني يخدم السوق العربي — remote-first.',
                'responsibilities' => ['Roadmap', 'User stories', 'Stakeholder management'],
                'requirements' => ['3+ سنوات PM', 'Agile/Scrum', 'Technical background'],
                'benefits' => ['Leadership role', 'USD', 'Global team'],
            ],
            [
                'title' => 'مطور Full Stack',
                'company_name' => 'GlobalTech Hiring',
                'logo' => '🌍',
                'location' => 'عن بُعد · عالمي',
                'employment_type' => 'دوام كامل',
                'salary_min' => 1800,
                'salary_max' => 2500,
                'remote_type' => 'full-remote',
                'timezone' => 'Flexible',
                'is_syria_friendly' => true,
                'payment_methods' => ['Wise', 'PayPal', 'Crypto'],
                'skills' => ['React', 'Node.js', 'AWS'],
                'tags' => ['full-time', 'remote', 'fullstack'],
                'tag_labels' => [
                    ['t' => 'عن بُعد 🌐', 'c' => 'teal'],
                    ['t' => 'Full Stack', 'c' => 'gold'],
                ],
                'tech_specialty' => 'Frontend',
                'is_new' => true,
                'is_featured' => false,
                'order' => 9,
                'published_at' => Carbon::now(),
                'description' => 'شركة أمريكية تستقطب مواهب سورية للعمل عن بُعد — full stack role.',
                'responsibilities' => ['End-to-end features', 'Code review', 'Architecture decisions'],
                'requirements' => ['5+ سنوات', 'React + Node', 'AWS basics', 'English fluent'],
                'benefits' => ['Top USD rates', 'US holidays', 'Equipment stipend'],
            ],
        ];

        foreach ($jobs as $item) {
            $specialtyName = $item['tech_specialty'];
            unset($item['tech_specialty']);

            $item['tech_specialty_id'] = $specialtyIds[$specialtyName] ?? null;
            $item['slug'] = Job::generateUniqueSlug($item['title']);
            $item['is_active'] = true;

            Job::firstOrCreate(
                ['title' => $item['title'], 'company_name' => $item['company_name']],
                $item
            );
        }
    }
}
