<?php

return [
    'shortcuts' => [
        [
            'title' => 'المستخدمون',
            'description' => 'إدارة المستخدمين',
            'route' => 'admin.users.index',
            'icon' => 'ri-group-line',
            'icon_color' => 'primary',
            'permission' => 'user-list',
        ],
        [
            'title' => 'الصلاحيات',
            'description' => 'إدارة الأدوار والصلاحيات',
            'route' => 'admin.roles.index',
            'icon' => 'ri-shield-check-line',
            'icon_color' => 'success',
        ],
        [
            'title' => 'المقالات',
            'description' => 'إدارة مقالات المدونة',
            'route' => 'admin.blog.posts.index',
            'icon' => 'ri-article-line',
            'icon_color' => 'info',
        ],
        [
            'title' => 'التصنيفات',
            'description' => 'تصنيفات المدونة',
            'route' => 'admin.blog.categories.index',
            'icon' => 'ri-folder-line',
            'icon_color' => 'warning',
        ],
        [
            'title' => 'رسائل التواصل',
            'description' => 'رسائل الزوار والتواصل',
            'route' => 'admin.contact-messages.index',
            'icon' => 'ri-mail-line',
            'icon_color' => 'cyan',
            'badge_key' => 'contact_unread',
        ],
        [
            'title' => 'النشرة البريدية',
            'description' => 'مشتركو النشرة',
            'route' => 'admin.newsletter-subscribers.index',
            'icon' => 'ri-mail-send-line',
            'icon_color' => 'purple',
        ],
        [
            'title' => 'طلبات الاستشارة',
            'description' => 'طلبات الاستشارة الواردة',
            'route' => 'admin.consultation-requests.index',
            'icon' => 'ri-calendar-check-line',
            'icon_color' => 'orange',
            'badge_key' => 'consultation_unread',
        ],
        [
            'title' => 'إعدادات الموقع',
            'description' => 'إعدادات عامة للموقع',
            'route' => 'admin.settings.site.index',
            'icon' => 'ri-settings-3-line',
            'icon_color' => 'secondary',
        ],
        [
            'title' => 'الذكاء الاصطناعي',
            'description' => 'مزودو AI والإعدادات',
            'route' => 'admin.ai.settings.index',
            'icon' => 'ri-robot-line',
            'icon_color' => 'primary',
        ],
        [
            'title' => 'واتساب',
            'description' => 'رسائل واتساب',
            'route' => 'admin.whatsapp-messages.index',
            'icon' => 'ri-whatsapp-line',
            'icon_color' => 'success',
        ],
        [
            'title' => 'الوسائط',
            'description' => 'مكتبة الوسائط',
            'route' => 'admin.media.index',
            'icon' => 'ri-image-line',
            'icon_color' => 'info',
            'permission' => 'media-list',
        ],
        [
            'title' => 'النسخ الاحتياطي',
            'description' => 'إدارة النسخ الاحتياطية',
            'route' => 'admin.backups.index',
            'icon' => 'ri-database-2-line',
            'icon_color' => 'danger',
        ],
    ],
];
